language: node_js

node_js:
  - "iojs"

addons:
  code_climate:
    repo_token: 2cf649b0c38dc112399b1f21a2b3aaf902874749

before_script:
  - npm install -g codeclimate-test-reporter
  - npm install -g codecov

after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha tests/*.js --reporter lcovonly -- -R spec
  - codeclimate-test-reporter < ./coverage/lcov.info
  - codecov
